### PR TITLE
Issue: #62 - UDP support

### LINKED ISSUE #62: UDP support

### PR DESCRIPTION
**Pull request by takeoverjp**
Hi,
This fixes #62.
I've confirmed that `nethogs -C` shows UDP bandwidth by process on Ubuntu 18.04 with iperf.
Thank you.

### CODE REVIEW

**Review by raboof — APPROVED** [review]
wow, very cool, thanks!

I wonder if this should be the default, rather than being hidden behind `-C`.

**Comment by takeoverjp** [comment]
Thank you so much for your rapid reply.

> I wonder if this should be the default, rather than being hidden behind -C.
It's good idea, but I'm afraid that the compatibility will be lost if so...

**Comment by takeoverjp** [comment]
Hi @raboof 
Sorry, I've found a bug that some invalid connections are shown after this commit.
I'll investigate it and update this branch later.

**Comment by takeoverjp** [comment]
Hi @raboof 
I've pushed 3 additional commits.

[1. ](https://github.com/raboof/nethogs/pull/199/commits/ccda1b50c4fdc1736c30e3b2d13a440c5552ae16) to avoid unneccessary computation when '-C' is not specified.
[2. ](https://github.com/raboof/nethogs/pull/199/commits/18629a3b33509e48167b86dacb4b10eb2a3e7015) to fix invalid connections.
[3. ](https://github.com/raboof/nethogs/pull/199/commits/b7a42786bd0f970eedbe3e5381290487c387f10f) to fix conninode_test build error.

About the 2nd commit, let me explain.

On short UDP traffic, pcap reports it, but we cannot find it in /proc/net/udp.
As the result, hash string named Process (like "10.244.25.52:36357-10.244.25.254:53") is created on each refresh,
even when same hash string named processes exist.
With [this commit](https://github.com/raboof/nethogs/pull/199/commits/18629a3b33509e48167b86dacb4b10eb2a3e7015), I add unlisted traffic as 'unknown UDP/TCP' Process.
This seems to work well in my environment.

As another option, we can treat unlisted traffic as hash string named process as it is,
and just avoid create new Process on each refresh.
How do you think?

**Comment by raboof** [comment]
> With this commit, I add unlisted traffic as 'unknown UDP/TCP' Process.

I guess that means if due to a race condition we see the packet before the entry shows up in /proc we will not recover from that later since we already added the connection to the 'unknown' list. Might be fine though - certainly better than creating a new process on each unrecognized package (which is what's happening now if I understand you correctly)

**Comment by raboof** [comment]
I'm ready to merge this PR if you're confident in it, let me know.

**Comment by takeoverjp** [comment]
Hi @raboof 
Thank you for your comment and review.

> I'm ready to merge this PR if you're confident in it, let me know.

Yes, please merge this PR.
Thank you.

**Comment by raboof** [comment]
Great contribution, thanks!

**Pull request merged**
