### PR TITLE
feat: Add basename support #155

### LINKED ISSUE #155: Long program name
My program names are really long due to being stored in nix store?

Is there a way to shorten to the basename? Similar to how htop is capable of doing this?

### PR DESCRIPTION
**Pull request by sgtcortez**
Hi, I did this simple implementation, hope it can be useful.

User, can have the choice to see only the program name, instead of the full path. 
It seems useful when you have a program that resides on a big directory hierarchy. 

I used the *b* flag, to enable/disable the short process name. I saw, that its the same flag to enable bug hunt mode. I can change, if you request. 

This is my first pull request on a project ... So, if I am doing something wrong, please, tell me! 

Thanks in advance ... 
Best Regards, Matheus Rambo. 

Closes #155

### CODE REVIEW

**Comment by sgtcortez** [comment]
As is: 
image

With the new feature:
image

**Comment by raboof** [comment]
Thanks for this contribution! I think this is a great feature, and perhaps should even be the default behavior.

I do think it would be nice if this behavior could also be switched from the command-line. It would be neat if the same key/letter could be used for the command-line switch and the interactive interface. Unfortunately `-b` is already taken, but it's a bit exotic anyway - you could move the bughunt mode to `-x`?

**Comment by sgtcortez** [comment]
Of course, change is on the way! 
Thanks for the reply! :)

**Comment by sgtcortez** [comment]
@raboof, please, take a look. Let me know if you find something! 

Thanks!

**Comment by raboof** [comment]
I think you also need to update the manpage in `doc/nethogs.8` - after that LGTM!

**Comment by sgtcortez** [comment]
Sorry, my bad.

**Review by raboof — APPROVED** [review]

**Comment by sgtcortez** [comment]
Done!

**Comment by raboof** [comment]
> Sorry, my bad.

No worries, nice contribution, thanks!

**Pull request merged**
