### PR TITLE
Use CPPFLAGS in Makefile

### PR DESCRIPTION
**Pull request by Rudloff**
Hello,

When you need to use a custom include directory, it is pretty useful to have a Makefile that uses CPPFLAGS.
(Also a lot of package managers use this flag to ensure the correct headers are used.)

### CODE REVIEW

**Comment by raboof** [comment]
I agree adding `CPPFLAGS` seems like a good idea - it's also part of the default rules in GNU Make (http://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html#Catalogue-of-Rules).

Perhaps we could make the Makefile a bit smarter so we can make more use of those automatically included rules?

**Comment by Rudloff** [comment]
I think it's a great idea but unfortunately I don't know enough about make to do this correctly.

**Comment by raboof** [comment]
Makes sense! Looks like the `CPPFLAGS` should come before the `CXXFLAGS`, though?

**Comment by Rudloff** [comment]
You're probably right, I changed the order.

**Pull request merged**
